#!/bin/bash

#
# Script to create virtual host for Nginx server
#
# @author   Saeed

export parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

source $parent_path/utilities.sh


server_name=$(hostname)

function install_stack() {
	bash $parent_path/scripts/stack/install.sh
}

function php_tools() {
	bash $parent_path/scripts/php/php-menu.sh
}

function nginx_tools() {
	bash $parent_path/scripts/nginx/nginx-menu.sh
}

function other_tools() {
	# _arrow "==================="
    # _arrow "Other Tools are Under Development"
	# _arrow "==================="

	# _continue

	bash $parent_path/scripts/other/other_menu.sh
}






menu(){
echo -ne "
$(pGreen '===== WSL Tools by SAEED -- Main MENU =====')

$(pGreen '1)') $(_underline 'Install Stacks')

$(pGreen '2)') PHP Tools

$(pGreen '3)') Nginx Tools

$(pGreen '4)') Other Tools

$(pGreen '0)') Exit
-----------------------------------
$(pBlue ':: Main Menu :: Choose an option:') "
        read a
        case $a in
	        1) install_stack ; menu ;;
	        2) php_tools ; menu ;;
	        3) nginx_tools ; menu ;;
	        4) other_tools ; menu ;;
		0) _success "Have a Nice Day, BYE BYE";exit 0 ;;
		*) _error "Wrong Choice !!";_continue; menu;;
        esac
}

#### MAIN START ###

menu